[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "chatgpt_voice_assistant"
version = "0.0.1"
authors = [
  { name="Jake Cyr", email="cyrjake@gmail.com" },
]
dependencies = [
  "openai",
  "SpeechRecognition",
  "pyaudio",
  "gtts",
]
description = "Package to speak with OpenAI's GPT-3 model"
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
  "pytest",
  "mock",
  "coverage",
  "black",
  "pylint",
  "isort",
  "mypy",
  "types-pyaudio",
  "types-mock",
]

[project.scripts]
chatgpt-assist = "chatgpt_voice_assistant.main:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "."
]

[tool.setuptools]
packages = ["chatgpt_voice_assistant"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
